[package]
name = "glslang"
version = "0.1.1"
edition = "2021"

description = "Rust bindings for glslang"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
once_cell = "1.19.0"
glslang-sys = { version = "0.1.0", path = "../glslang-sys" }
thiserror = "1.0"
rustc-hash = "1.1.0"

[dev-dependencies]
rspirv = "0.12.0"